# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CadsFlatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Start(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Start()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStart(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Start
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Start
    def LuaCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StartStart(builder): builder.StartObject(1)
def Start(builder):
    return StartStart(builder)
def StartAddLuaCode(builder, luaCode): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(luaCode), 0)
def AddLuaCode(builder, luaCode):
    return StartAddLuaCode(builder, luaCode)
def StartEnd(builder): return builder.EndObject()
def End(builder):
    return StartEnd(builder)