// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CadsFlatbuffers
{

public enum MsgContents : byte
{
  NONE = 0,
  Start = 1,
  Stop = 2,
  Profile = 3,
};


}
