// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CadsFlatbuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Start : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static Start GetRootAsStart(ByteBuffer _bb) { return GetRootAsStart(_bb, new Start()); }
  public static Start GetRootAsStart(ByteBuffer _bb, Start obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Start __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LuaCode { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLuaCodeBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLuaCodeBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLuaCodeArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<CadsFlatbuffers.Start> CreateStart(FlatBufferBuilder builder,
      StringOffset lua_codeOffset = default(StringOffset)) {
    builder.StartTable(1);
    Start.AddLuaCode(builder, lua_codeOffset);
    return Start.EndStart(builder);
  }

  public static void StartStart(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLuaCode(FlatBufferBuilder builder, StringOffset luaCodeOffset) { builder.AddOffset(0, luaCodeOffset.Value, 0); }
  public static Offset<CadsFlatbuffers.Start> EndStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CadsFlatbuffers.Start>(o);
  }
}


}
