// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using caas_gui.Data;

#nullable disable

namespace caasgui.Migrations
{
    [DbContext(typeof(PostgresDBContext))]
    [Migration("20230619105514_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("caas_gui.Data.Device", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Serial"));

                    b.Property<string>("LuaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MsgSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("State")
                        .HasColumnType("bigint");

                    b.HasKey("Serial");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
