// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cads_gui.Data;

#nullable disable

namespace cadsgui.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    partial class SQLiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("cads_gui.Data.Belt", b =>
                {
                    b.Property<long>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("WidthN")
                        .HasColumnType("REAL");

                    b.Property<double>("Ymax")
                        .HasColumnType("REAL");

                    b.Property<double>("YmaxN")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("chrono")
                        .HasColumnType("TEXT");

                    b.Property<string>("conveyor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("x_res")
                        .HasColumnType("REAL");

                    b.Property<double>("y_res")
                        .HasColumnType("REAL");

                    b.Property<double>("z_max")
                        .HasColumnType("REAL");

                    b.Property<double>("z_min")
                        .HasColumnType("REAL");

                    b.Property<double>("z_off")
                        .HasColumnType("REAL");

                    b.Property<double>("z_res")
                        .HasColumnType("REAL");

                    b.HasKey("rowid");

                    b.ToTable("belt");
                });

            modelBuilder.Entity("cads_gui.Data.Conveyors", b =>
                {
                    b.Property<long>("rowid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Belt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("rowid");

                    b.ToTable("Conveyors");
                });

            modelBuilder.Entity("cads_gui.Data.SavedZDepthParams", b =>
                {
                    b.Property<string>("Conveyor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Depth")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.ToTable("SavedZDepthParams");
                });
#pragma warning restore 612, 618
        }
    }
}
